AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    MemorySize: 128
    Timeout: 15
Resources:
  extractFeaturesBucket:
    Type: AWS::S3::Bucket
  accessDBBucket:
    Type: AWS::S3::Bucket
  ExtractFeaturesLambdaHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://datapreprocessing/1f3f15272cad74a30aa857eccdaf23d8
      Handler: src/handlers/extractFeatures.handler
      Description: Function is called when a file is stored in S3.
      Runtime: nodejs12.x
      Events:
        S3Bucket:
          Type: S3
          Properties:
            Bucket:
              Ref: extractFeaturesBucket
            Events: s3:ObjectCreated:*
  AccessDBHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://datapreprocessing/40cfe5c46f2dc84aa346a015e3f34a22
      Handler: src/handlers/accessDBHandler.handler
      Description: Function is called when a file is stored in S3.
      Runtime: nodejs12.x
      Events:
        S3Bucket:
          Type: S3
          Properties:
            Bucket:
              Ref: accessDBBucket
            Events: s3:ObjectCreated:*
  AllowlambdaS3ToCallLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Ref: ExtractFeaturesLambdaHandler
      Principal: s3.amazonaws.com
      SourceArn:
        Fn::GetAtt:
        - extractFeaturesBucket
        - Arn
  AllowS3ToCallLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Ref: AccessDBHandler
      Principal: s3.amazonaws.com
      SourceArn:
        Fn::GetAtt:
        - accessDBBucket
        - Arn
